name: Goolge Services Testing...

on: [push]


jobs:
  build:
    name: Google Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    # Setup gcloud CLI
    - uses: mchirico/gcp-actions@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.OWNER }}


    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker


    - run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64  && sudo install minikube-linux-amd64 /usr/local/bin/minikube


    - run: |
        # View storage
        gcloud version
        gsutil ls
        gcloud components install minikube --quiet
        gcloud components install kubectl --quiet

    - run: |
        sudo minikube start --vm-driver=none
        echo $USER $HOME



    # BigQuery
    - name: Working with BigQuery
      run: |
       txt="robinpig " 
       bq query --nouse_legacy_sql 'CREATE TABLE IF NOT EXISTS  `robinpig.github.log` (msg string, timeEnter timestamp);'
       bq query --nouse_legacy_sql  --parameter=MSG:STRING:"${txt}"  'insert into `robinpig.github.log` (msg,timeEnter) values (@MSG,CURRENT_TIMESTAMP())'




